apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: case-service
  namespace: oda
spec:
  service:
    name: case-service
  calls:
    - name: db
---
apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: deduction-service
  namespace: oda
spec:
  service:
    name: deduction-service
  calls:
    - name: db
---
apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: evidence-service
  namespace: oda
spec:
  service:
    name: evidence-service
  calls:
    - name: db
---
apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: game-service
  namespace: oda
spec:
  service:
    name: game-service
  calls:
    - name: case-service
    - name: deduction-service
    - name: evidence-service
    - name: interrogation-service
    - name: player-service
---
apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: interrogation-service
  namespace: oda
spec:
  service:
    name: interrogation-service
  calls:
    - name: db
---
apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: player-service
  namespace: oda
spec:
  service:
    name: player-service
  calls:
    - name: db
